
const J=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}});
const uid=()=>crypto.randomUUID();const bytes=n=>crypto.getRandomValues(new Uint8Array(n));const b64=a=>btoa(String.fromCharCode(...a));
async function hash(pin,salt){let key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);let bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(atob(salt),c=>c.charCodeAt(0)),iterations:120000,hash:'SHA-256'},key,256);return b64(new Uint8Array(bits))}
function cookie(req){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
async function auth(c){let sid=cookie(c.request).mf_session;if(!sid)return null;let r=await c.env.DB.prepare('SELECT u.id,u.name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?').bind(sid,new Date().toISOString()).first();return r}
const fields={accounts:['name','type','balance'],cards:['name','card_limit','closing_day','due_day'],transactions:['account_id','date','due_date','description','type','category','status','value'],card_transactions:['card_id','purchase_date','invoice_month','description','category','installment','status','value'],budgets:['category','value'],goals:['name','target','current_value','target_date']};
export async function onRequest(c){try{let url=new URL(c.request.url),parts=url.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean),route=parts[0]||'',id=parts[1],m=c.request.method;
if(route==='register'&&m==='POST'){let b=await c.request.json(),name=String(b.name||'').trim(),pin=String(b.pin||'');if(!name||pin.length<4)return J({error:'Informe nome e PIN com pelo menos 4 caracteres.'},400);let salt=b64(bytes(16)),ph=await hash(pin,salt),user=uid();try{await c.env.DB.prepare('INSERT INTO users VALUES(?,?,?,?,?)').bind(user,name,ph,salt,new Date().toISOString()).run()}catch{return J({error:'Nome de usuário já utilizado.'},409)}await c.env.DB.prepare('INSERT INTO accounts VALUES(?,?,?,?,?)').bind(uid(),user,'Conta principal','Conta corrente',0).run();return J({ok:true},201)}
if(route==='login'&&m==='POST'){let b=await c.request.json(),u=await c.env.DB.prepare('SELECT * FROM users WHERE name=?').bind(String(b.name||'').trim()).first();if(!u||await hash(String(b.pin||''),u.salt)!==u.password_hash)return J({error:'Usuário ou PIN incorreto.'},401);let sid=uid(),exp=new Date(Date.now()+7*864e5).toISOString();await c.env.DB.prepare('DELETE FROM sessions WHERE expires_at<=?').bind(new Date().toISOString()).run();await c.env.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(sid,u.id,exp).run();return J({user:{id:u.id,name:u.name}},200,{'set-cookie':`mf_session=${sid}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`})}
if(route==='logout'&&m==='POST'){let sid=cookie(c.request).mf_session;if(sid)await c.env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(sid).run();return J({ok:true},200,{'set-cookie':'mf_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
let user=await auth(c);if(!user)return J({error:'Não autenticado.'},401);if(route==='me')return J({user});
if(route==='sync'&&m==='GET'){let out={user,accounts:[],cards:[],transactions:[],card_transactions:[],budgets:[],goals:[]};for(let t of Object.keys(fields)){out[t]=(await c.env.DB.prepare(`SELECT * FROM ${t} WHERE user_id=?`).bind(user.id).all()).results}return J(out)}
if(!fields[route])return J({error:'Rota não encontrada.'},404);
if(m==='GET'){let r=await c.env.DB.prepare(`SELECT * FROM ${route} WHERE user_id=? ORDER BY rowid DESC`).bind(user.id).all();return J(r.results)}
if(m==='POST'){let b=await c.request.json(),cols=fields[route],rid=uid(),vals=cols.map(k=>b[k]??null);await c.env.DB.prepare(`INSERT INTO ${route}(id,user_id,${cols.join(',')}) VALUES(?,?${',?'.repeat(cols.length)})`).bind(rid,user.id,...vals).run();return J({id:rid},201)}
if(m==='PUT'&&id){let b=await c.request.json(),cols=fields[route].filter(k=>k in b);if(!cols.length)return J({error:'Sem alterações.'},400);await c.env.DB.prepare(`UPDATE ${route} SET ${cols.map(k=>k+'=?').join(',')} WHERE id=? AND user_id=?`).bind(...cols.map(k=>b[k]),id,user.id).run();return J({ok:true})}
if(m==='DELETE'&&id){await c.env.DB.prepare(`DELETE FROM ${route} WHERE id=? AND user_id=?`).bind(id,user.id).run();return J({ok:true})}return J({error:'Método não permitido.'},405)
}catch(e){return J({error:'Erro interno.',detail:String(e.message||e)},500)}}
