
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,salt TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL,balance REAL NOT NULL DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS cards(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,card_limit REAL NOT NULL DEFAULT 0,closing_day INTEGER,due_day INTEGER,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,account_id TEXT,date TEXT NOT NULL,due_date TEXT,description TEXT NOT NULL,type TEXT NOT NULL,category TEXT NOT NULL,status TEXT NOT NULL,value REAL NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS card_transactions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,card_id TEXT NOT NULL,purchase_date TEXT NOT NULL,invoice_month TEXT NOT NULL,description TEXT NOT NULL,category TEXT NOT NULL,installment TEXT,status TEXT NOT NULL,value REAL NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS budgets(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,category TEXT NOT NULL,value REAL NOT NULL,UNIQUE(user_id,category),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS goals(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,target REAL NOT NULL,current_value REAL NOT NULL DEFAULT 0,target_date TEXT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_tx_user_date ON transactions(user_id,date);CREATE INDEX IF NOT EXISTS idx_ctx_user_invoice ON card_transactions(user_id,invoice_month);CREATE INDEX IF NOT EXISTS idx_sessions_exp ON sessions(expires_at);
